int cvi_board_init(void)
{
#if 0 /* pinmux set in alios */
	PINMUX_CONFIG(CAM_MCLK0, CAM_MCLK0);

	PINMUX_CONFIG(IIC2_SCL, IIC2_SCL);
	PINMUX_CONFIG(IIC2_SDA, IIC2_SDA);

	PINMUX_CONFIG(IIC3_SCL, IIC3_SCL);
	PINMUX_CONFIG(IIC3_SDA, IIC3_SDA);
#endif

	//enable pwm
	mmio_setbits_32(0x030002d0, 1 << 9);

	/* AIC8800 WiFi module */
	pinmux_config(PINMUX_SDIO1);
	PINMUX_CONFIG(SPK_EN, XGPIOA_15);	// WIFI_PWR_EN
	PINMUX_CONFIG(CLK32K, PWR_GPIO_10);	// HOST_WAKE_BT

	/* AIC8800 Bluetooth Serial */
	PINMUX_CONFIG(UART2_RX, UART2_RX);
	PINMUX_CONFIG(UART2_TX, UART2_TX);
	PINMUX_CONFIG(UART2_CTS, UART2_CTS);
	PINMUX_CONFIG(UART2_RTS, UART2_RTS);

	/* CSI Camera J2 */
	PINMUX_CONFIG(IIC2_SDA, IIC2_SDA);
	PINMUX_CONFIG(IIC2_SCL, IIC2_SCL);
	PINMUX_CONFIG(CAM_MCLK1, CAM_MCLK1);
	PINMUX_CONFIG(CAM_PD1, XGPIOA_4);

	/* AliOS debug serial */
	PINMUX_CONFIG(JTAG_CPU_TCK, UART1_RX);
	PINMUX_CONFIG(JTAG_CPU_TMS, UART1_TX);

	/* USB control signal */
	PINMUX_CONFIG(USB_VBUS_EN, XGPIOB_5);
	PINMUX_CONFIG(AUX0, XGPIOA_30);

	return 0;
}
